CREATE TABLE `tp_knowledge` (
  `KNOWLEDGE_NO` bigint(20) NOT NULL COMMENT '',
  `KNOWLEDGE_NAME` varchar(100) DEFAULT NULL COMMENT '',
  `KNOWLEDGE_IMG` text COMMENT '',
  `KNOWLEDGE_STATUS` char(1) DEFAULT NULL COMMENT '',
  `DATE_CREATED` datetime DEFAULT NULL COMMENT '',
  `LAST_UPDATED` datetime DEFAULT NULL COMMENT '',
  PRIMARY KEY (`KNOWLEDGE_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT=''